### ISSUE TITLE
Use schema.org to improve voice search

### ISSUE THREAD

**Issue by estudodv** [feyuk/html-seo-template-2024#1]
How can schema.org be leveraged to improve voice search and conversational AI interactions, specifically for complex entities like multi-step recipes or product specifications with interdependencies, while considering potential limitations of voice-based communication like ambiguity and incomplete information?

**Comment by feyuk** [comment]
Utilizing nested schema structures within recipes (Recipe, RecipeStep, Ingredient) and detailed product specifications (ProductModel, FeatureList, Feature, Compatibility) alongside structured data markup can guide voice AI in understanding complex entities.
